# Generated by Django 4.2 on 2025-04-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
    ]
