# Generated by Django 4.2 on 2025-04-10 17:20

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
